name: Build .deb package and add record in RELEASES tab
on:
    push:
        branches:
            - worlderp/master
jobs:
    fetch-upstream:
        runs-on: ubuntu-latest
        steps:
            #     Set global environment variables:
            -   uses: actions/checkout@v2
            -   name: Set global env
                id: global_env
                run: |
                    echo "::set-output name=TARGET_BRANCH::worlderp/master"
            -   name: Checkout target repo
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.event.repository.default_branch }}
                    fetch-depth: 0
            -   name: Install node
                uses: actions/setup-node@v2
                with:
                    node-version: '14'
            -   name: Build
                run: |
                    npm install
                    make
                    dpkg-buildpackage -A -rfakeroot -us -uc -tc
