name: Build .deb package and add record in RELEASES tab
on:
    push:
        branches:
            - worlderp/master
jobs:
    build-release:
        runs-on: ubuntu-latest
        steps:
            #     Set global environment variables:
            -   uses: actions/checkout@v2
            -   name: Set global env
                id: global_env
                run: |
                    echo "::set-output name=TARGET_BRANCH::worlderp/master"
            -   name: Checkout target repo
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.event.repository.default_branch }}
            -   name: Install node
                uses: actions/setup-node@v2
                with:
                    node-version: '14'
            -   name: Build package
                run: |
                    npm install
                    make
            -   name: Package .deb
                uses: singingwolfboy/build-dpkg-stretch@v1
                id: build_dpkg
                with:
                    args: -A -rfakeroot -us -uc -tc

            -   name: test
                if: always()
                run: |
                    echo ${{ steps.build.outputs.filename }}
                    echo ${{ steps.build.outputs.filename-dbgsym }}