name: fetch-upstream
on:
    push:
#    schedule:
#        - cron: '* 0/6 * * MON-FRI'
jobs:
    fetch-upstream:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout target master branch
                uses: actions/checkout@v2
                with:
                    ref: worlderp/master
                     fetch-depth: 0
            #     Set global environment variables:
            -   name: Set global env
                id: global_env
                run: |
                    localReleaseVersion=$(git describe --tags --abbrev=0 | grep stable | cut -d '_' -f 2)
                    upstreamReleaseVersion =$(git ls-remote --refs https://github.com/jitsi/jitsi-meet  | grep stable | cut -d '_' -f 2 | sort -nr | head -1)
                    echo "::set-output name=LOCAL_RELEASE::localReleaseVersion"
                    echo "::set-output name=UPSTREAM_RELEASE::$upstreamReleaseVersion"

#git tag -l | grep stable | cut -d '_' -f 2 | sort -nr | head -1
#git ls-remote --refs https://github.com/jitsi/jitsi-meet  | grep stable | cut -d '_' -f 2 | sort -nr | head -1