name: fetch-upstream
on:
    push:
#    schedule:
#        - cron: '* 0/6 * * MON-FRI'
jobs:
    fetch-upstream:
        runs-on: ubuntu-latest
        steps:
            #     Set global environment variables:
            -   uses: actions/checkout@v2
            -   name: Set global env
                id: global_env
                run: |
                    upstreamReleaseVersion=$(git ls-remote --refs https://github.com/jitsi/jitsi-meet  | awk -F "_" '/stable/{print $2}' | sort -nr | head -1)
                    stableBranchName="stable/$(git ls-remote --refs https://github.com/jitsi/jitsi-meet | awk -F "/"  '/stable\/jitsi-meet_'$upstreamReleaseVersion'/{print $4}')"
                    echo "::set-output name=RELEASE_BRANCH_NAME::$stableBranchName"
                    echo "::set-output name=UPSTREAM_RELEASE::$upstreamReleaseVersion"
                    echo "::set-output name=TARGET_BRANCH::worlderp/master"
                    echo $upstreamReleaseVersion
                    echo $stableBranchName
            -   name: Checkout target master branch
                uses: actions/checkout@v2
                with:
                    ref: master
                    fetch-depth: 0
            -   name: Sync upstream changes
                id: sync
                uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
                with:
                    target_sync_branch: master
                    target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                    upstream_sync_branch: master
                    upstream_sync_repo: jitsi/jitsi-meet
            -   uses: actions/checkout@v2
            -   name: TEST
                run: |
                    echo git fetch upstream
                    git fetch upstream
                    echo $(git tag -l | awk -F "_" '/stable/{print $2}' | sort -nr | head -1)

#            -   name: Checkout target worlerp/master branch
#                uses: actions/checkout@v2
#                with:
#                    ref: ${{ steps.global_env.outputs.TARGET_BRANCH }}
#                    fetch-depth: 0