name: fetch-upstream
on:
    push:
#    schedule:
#        - cron: '* 0/6 * * MON-FRI'
jobs:
    fetch-upstream:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout target master branch
                uses: actions/checkout@v2
                with:
                    ref: master
                    fetch-depth: 0
            -   name: Sync upstream changes
                id: sync
                uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
                with:
                    target_sync_branch: master
                    target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                    upstream_sync_branch: master
                    upstream_sync_repo: jitsi/jitsi-meet
            -   name: Checkout target worlerp/master branch
                uses: actions/checkout@v2
                with:
                    ref: worlderp/master
                    fetch-depth: 0
            #     Set global environment variables:
            -   name: Set global env
                id: global_env
                run: |
                    upstreamReleaseVersion=$(git ls-remote --refs https://github.com/jitsi/jitsi-meet  | awk -F "_" '/stable/{print $2}' | sort -nr | head -1)
                    stableBranchName="stable/$(git ls-remote --refs https://github.com/jitsi/jitsi-meet | awk -F "/"  '/stable\/jitsi-meet_'$upstreamReleaseVersion'/{print $4}')"
                    echo "::set-output name=LOCAL_RELEASE::$localReleaseVersion"
                    echo "::set-output name=UPSTREAM_RELEASE::$upstreamReleaseVersion"
                    echo "${stableBranchName}"
                    echo "${upstreamReleaseVersion}"

#git tag -l | awk -F "_" '/stable/{print $2}' | sort -nr | head -1
#git ls-remote --refs https://github.com/jitsi/jitsi-meet  | awk -F "_" '/stable/{print $2}' | sort -nr | head -1