name: fetch-upstream
on:
    schedule:
        -   cron: '* 0/6 * * MON-FRI'
jobs:
    fetch-upstream:
        runs-on: ubuntu-latest
        steps:
            #     Set global environment variables:
            -   uses: actions/checkout@v2
            -   name: Set global env
                id: global_env
                run: |
                    echo "::set-output name=TARGET_BRANCH::worlderp/master"
            -   name: Checkout target repo
                uses: actions/checkout@v2
                with:
                    ref: master
            -   name: Sync upstream changes
                id: sync
                uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
                with:
                    target_sync_branch: master
                    target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                    upstream_sync_branch: master
                    upstream_sync_repo: jitsi/jitsi-meet
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ steps.global_env.outputs.TARGET_BRANCH }}
                    fetch-depth: 0
            -   name: Merge latest release
                run: |
                    upstreamReleaseVersion=$(git tag -l | awk -F "_" '/stable/{print $2}' | sort -nr | head -1)
                    stableBranchName="stable/$(git tag -l | awk -F "/"  '/stable\/jitsi-meet_'$upstreamReleaseVersion'/{print $2}')"
                    echo $upstreamReleaseVersion
                    echo $stableBranchName
                    git merge $stableBranchName
            -   name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ steps.global_env.outputs.TARGET_BRANCH }}